import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, Bell, Box, ChevronLeft, CircleDollarSign, Download, FileText, LayoutDashboard, Menu, PackagePlus, Plus, Search, Settings, Smartphone, Trash2, Users, X } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || `${window.location.origin}/api`;
const navItems = [
  { label: 'نظرة عامة', icon: LayoutDashboard },
  { label: 'المنتجات والمخزون', icon: Box },
  { label: 'الفواتير', icon: FileText },
  { label: 'العملاء', icon: Users },
  { label: 'المدفوعات', icon: CircleDollarSign },
];
const fallbackProducts = [
  { name: 'iPhone 15 Pro Max', type: 'موبايل', quantity: 8, sellingPrice: 54500, minQuantity: 3 },
  { name: 'Samsung Galaxy S24 Ultra', type: 'موبايل', quantity: 5, sellingPrice: 42000, minQuantity: 3 },
  { name: 'AirPods Pro 2', type: 'إكسسوار', quantity: 14, sellingPrice: 8750, minQuantity: 5 },
  { name: 'شاحن Baseus 65W', type: 'إكسسوار', quantity: 2, sellingPrice: 1250, minQuantity: 5 },
];
const money = (value) => `${Number(value || 0).toLocaleString('ar-EG')} ج.م`;
const date = (value) => value ? new Date(value).toLocaleDateString('ar-EG', { day: 'numeric', month: 'short', year: 'numeric' }) : '-';
const initials = (name = '') => name.split(' ').slice(0, 2).map((word) => word[0]).join('');
async function request(path, options) { const response = await fetch(`${API}${path}`, options); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body?.message || 'حدث خطأ غير متوقع'); return body; }

function App() {
  const [page, setPage] = useState('نظرة عامة');
  const [products, setProducts] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [invoices, setInvoices] = useState([]);
  const [payments, setPayments] = useState([]);
  const [connected, setConnected] = useState(false);
  const [modal, setModal] = useState(null);
  const [toast, setToast] = useState('');
  const [mobileNav, setMobileNav] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [installPrompt, setInstallPrompt] = useState(null);
  const [storeName, setStoreName] = useState(() => {
    const savedName = localStorage.getItem('mobile-shop-name');
    return !savedName || savedName === 'موبايل ستور' ? 'Omar Shop' : savedName;
  });
  const [defaultMinQuantity, setDefaultMinQuantity] = useState(() => Number(localStorage.getItem('mobile-shop-min-quantity') || 3));

  async function loadData() {
    try {
      const data = await Promise.all([request('/products'), request('/customers'), request('/invoices'), request('/payments')]);
      setProducts(data[0]); setCustomers(data[1]); setInvoices(data[2]); setPayments(data[3]); setConnected(true);
    } catch { setConnected(false); setProducts((current) => current.length ? current : fallbackProducts); }
  }
  useEffect(() => { loadData(); }, []);
  useEffect(() => {
    const handleInstallPrompt = (event) => {
      event.preventDefault();
      setInstallPrompt(event);
    };
    window.addEventListener('beforeinstallprompt', handleInstallPrompt);
    return () => window.removeEventListener('beforeinstallprompt', handleInstallPrompt);
  }, []);
  async function installApp() {
    if (!installPrompt) return;
    await installPrompt.prompt();
    setInstallPrompt(null);
  }
  function notify(message) { setToast(message); window.setTimeout(() => setToast(''), 3000); }
  async function save(path, body, message) { try { await request(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await loadData(); setModal(null); notify(message); } catch (error) { notify(error.message); } }
  async function deleteProduct(id) { if (!id || !window.confirm('هل تريد حذف المنتج؟')) return; try { await request(`/products/${id}`, { method: 'DELETE' }); await loadData(); notify('تم حذف المنتج'); } catch (error) { notify(error.message); } }
  function goTo(nextPage) { setPage(nextPage); setMobileNav(false); }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}>
      <div className="brand"><img className="brand-image" src="/omar-shop-phone.svg" alt="شعار Omar Shop" /><span>Omar Shop</span><small>POS</small></div>
      <div className="store-switcher"><span className="store-avatar">م</span><span><strong>{storeName}</strong><small>الفرع الرئيسي</small></span><ChevronLeft size={16} /></div>
      <p className="nav-label">القائمة الرئيسية</p>
      <nav>{navItems.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${page === label ? 'active' : ''}`} onClick={() => goTo(label)}><Icon size={18} /><span>{label}</span>{label === 'المنتجات والمخزون' && <i>{products.filter((product) => product.quantity <= product.minQuantity).length || ''}</i>}</button>)}</nav>
      <div className="sidebar-footer"><button className="nav-item" onClick={() => setModal('settings')}><Settings size={18} /><span>الإعدادات</span></button><div className="profile"><span className="profile-avatar">ع</span><span><strong>عمر السمان</strong><small>مدير النظام</small></span><ChevronLeft size={16} /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)}><Menu size={21} /></button><div className="breadcrumbs"><span>الرئيسية</span><ChevronLeft size={14} /><strong>{page}</strong></div><div className="top-actions">{installPrompt && <button className="install-button" onClick={installApp}><Download size={15} /> تثبيت التطبيق</button>}<button className="icon-button" onClick={() => setNotificationsOpen(!notificationsOpen)} aria-label="التنبيهات"><Bell size={19} /><i /></button><div className="top-date">الثلاثاء، ٢٣ سبتمبر ٢٠٢٦</div>{notificationsOpen && <div className="notification-popover"><strong>التنبيهات</strong><span>{products.filter((product) => product.quantity <= product.minQuantity).length} منتجات مخزونها منخفض</span><button onClick={() => { goTo('المنتجات والمخزون'); setNotificationsOpen(false); }}>مراجعة المخزون</button></div>}</div></header>
      <div className="content-wrap"><div className={`connection-status ${connected ? 'connected' : ''}`}><span />{connected ? 'متصل بقاعدة البيانات' : 'تعذر الاتصال بقاعدة البيانات'}</div>
        {page === 'نظرة عامة' && <Dashboard products={products} customers={customers} invoices={invoices} onNavigate={goTo} onAdd={() => setModal('product')} onDelete={deleteProduct} />}
        {page === 'المنتجات والمخزون' && <ProductsPage products={products} onAdd={() => setModal('product')} onDelete={deleteProduct} />}
        {page === 'العملاء' && <CustomersPage customers={customers} onAdd={() => setModal('customer')} />}
        {page === 'الفواتير' && <InvoicesPage invoices={invoices} customers={customers} products={products} onAdd={() => setModal('invoice')} />}
        {page === 'المدفوعات' && <PaymentsPage payments={payments} invoices={invoices} customers={customers} onAdd={() => setModal('payment')} />}
      </div>
    </main>
    {modal === 'product' && <ProductModal onClose={() => setModal(null)} onSave={(body) => save('/products', body, 'تم حفظ المنتج في قاعدة البيانات')} />}
    {modal === 'customer' && <CustomerModal onClose={() => setModal(null)} onSave={(body) => save('/customers', body, 'تم حفظ العميل')} />}
    {modal === 'invoice' && <InvoiceModal products={products} customers={customers} onClose={() => setModal(null)} onSave={(body) => save('/invoices', body, 'تم إنشاء الفاتورة وتحديث المخزون')} />}
    {modal === 'payment' && <PaymentModal invoices={invoices} customers={customers} onClose={() => setModal(null)} onSave={(body) => save('/payments', body, 'تم تسجيل الدفعة')} />}
    {modal === 'settings' && <SettingsModal storeName={storeName} defaultMinQuantity={defaultMinQuantity} onClose={() => setModal(null)} onSave={({ name, minQuantity }) => { localStorage.setItem('mobile-shop-name', name); localStorage.setItem('mobile-shop-min-quantity', String(minQuantity)); setStoreName(name); setDefaultMinQuantity(minQuantity); setModal(null); notify('تم حفظ الإعدادات'); }} />}
    {toast && <div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}

function PageHeader({ eyebrow, title, description, action, onAction }) { return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p></div>{action && <button className="primary-button" onClick={onAction}><Plus size={17} /> {action}</button>}</section>; }
function PanelHeading({ title, action, onAction }) { return <div className="panel-heading"><h2>{title}</h2>{action && <button className="panel-action" onClick={onAction}>{action}<ChevronLeft size={14} /></button>}</div>; }
function StatCard({ label, value, suffix, change, icon: Icon, tone }) { return <div className={`stat-card ${tone}`}><div className="stat-top"><span className="stat-icon"><Icon size={19} /></span><span className="stat-change up">{change}</span></div><p>{label}</p><div className="stat-value">{value}<small>{suffix}</small></div></div>; }
function Dashboard({ products, customers, invoices, onNavigate, onAdd, onDelete }) { const low = products.filter((product) => product.quantity <= product.minQuantity); const sales = invoices.reduce((sum, invoice) => sum + invoice.subtotal, 0); return <><PageHeader eyebrow="صباح الخير يا عمر" title="نظرة عامة" description="تابع حركة متجرك اليوم واتخذ قرارات أسرع." action="إضافة منتج" onAction={onAdd} /><section className="stats-grid"><StatCard label="إجمالي المبيعات" value={sales.toLocaleString('ar-EG')} suffix="ج.م" change="مباشر" icon={CircleDollarSign} tone="navy" /><StatCard label="إجمالي الفواتير" value={invoices.length.toLocaleString('ar-EG')} suffix="فاتورة" change="كل الوقت" icon={FileText} tone="teal" /><StatCard label="إجمالي المنتجات" value={products.length.toLocaleString('ar-EG')} suffix="منتج" change={`${low.length} منخفض`} icon={Box} tone="orange" /><StatCard label="عملاء لديهم رصيد" value={customers.filter((customer) => customer.balance > 0).length.toLocaleString('ar-EG')} suffix="عميل" change={money(customers.reduce((sum, customer) => sum + customer.balance, 0))} icon={Users} tone="plum" /></section><section className="dashboard-grid"><div className="panel sales-panel"><PanelHeading title="ملخص المبيعات" action="عرض الفواتير" onAction={() => onNavigate('الفواتير')} /><div className="summary-big">{money(sales)}</div><p className="muted">المبيعات المسجلة في النظام حتى الآن</p><div className="summary-bars"><span style={{ height: '35%' }} /><span style={{ height: '53%' }} /><span style={{ height: '44%' }} /><span style={{ height: '72%' }} /><span style={{ height: '58%' }} /><span style={{ height: '86%' }} /><span style={{ height: '68%' }} /></div><div className="chart-days"><span>السبت</span><span>الأحد</span><span>الإثنين</span><span>الثلاثاء</span><span>الأربعاء</span><span>الخميس</span><span>الجمعة</span></div></div><div className="panel alerts-panel"><PanelHeading title="تنبيهات المخزون" action="عرض الكل" onAction={() => onNavigate('المنتجات والمخزون')} /><div className="alert-summary"><div><strong>{low.length}</strong><span>منتجات تحتاج إعادة طلب</span></div><AlertTriangle size={22} /></div>{low.slice(0, 3).map((product) => <div className="alert-row" key={product._id || product.name}><span className="alert-product"><span className="mini-box"><Box size={15} /></span><span><strong>{product.name}</strong><small>متبقي {product.quantity} فقط</small></span></span><ChevronLeft size={15} /></div>)}</div></section><section className="panel inventory-panel"><PanelHeading title="حالة المخزون" action="إدارة المنتجات" onAction={() => onNavigate('المنتجات والمخزون')} /><ProductTable products={products.slice(0, 5)} onDelete={onDelete} /></section></>; }
function ProductTable({ products, onDelete }) { return <div className="table-scroll"><table><thead><tr><th>المنتج</th><th>النوع</th><th>الكمية</th><th>سعر البيع</th><th>الحالة</th><th /></tr></thead><tbody>{products.map((product) => <tr key={product._id || product.name}><td><div className="product-cell"><span className="product-thumb blue"><Smartphone size={18} /></span><strong>{product.name}</strong></div></td><td>{product.type}</td><td><strong>{product.quantity}</strong> قطعة</td><td className="price">{money(product.sellingPrice)}</td><td><span className={`stock-badge ${product.quantity <= product.minQuantity ? 'low' : 'good'}`}>{product.quantity <= product.minQuantity ? 'مخزون منخفض' : 'متوفر'}</span></td><td>{product._id && <button className="icon-delete" onClick={() => onDelete(product._id)}><Trash2 size={14} /></button>}</td></tr>)}</tbody></table>{!products.length && <EmptyState text="لا توجد منتجات بعد" />}</div>; }
function ProductsPage({ products, onAdd, onDelete }) { const [query, setQuery] = useState(''); const filtered = products.filter((product) => product.name.includes(query) || product.type.includes(query)); return <><PageHeader eyebrow="المخزون" title="المنتجات والمخزون" description="أضف منتجاتك وتابع الكميات والأسعار وحدود التنبيه." action="إضافة منتج" onAction={onAdd} /><section className="panel"><div className="table-toolbar"><div className="search-box"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث عن منتج أو نوع..." /></div><span className="result-count">{filtered.length} منتج</span></div><ProductTable products={filtered} onDelete={onDelete} /></section></>; }
function CustomersPage({ customers, onAdd }) { return <><PageHeader eyebrow="العلاقات" title="العملاء" description="ملف كامل للعملاء والأرصدة المستحقة." action="إضافة عميل" onAction={onAdd} /><section className="panel"><PanelHeading title="كل العملاء" /><div className="table-scroll"><table><thead><tr><th>العميل</th><th>الهاتف</th><th>العنوان</th><th>الرصيد</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer._id}><td><div className="customer-cell"><span className="customer-avatar">{initials(customer.name)}</span><strong>{customer.name}</strong></div></td><td dir="ltr">{customer.phone}</td><td>{customer.address || 'بدون عنوان'}</td><td className="price">{money(customer.balance)}</td></tr>)}</tbody></table>{!customers.length && <EmptyState text="لم يتم تسجيل عملاء بعد" />}</div></section></>; }
function InvoicesPage({ invoices, customers, products, onAdd }) { return <><PageHeader eyebrow="المبيعات" title="الفواتير" description="أنشئ فواتير جديدة وراجع حالة المدفوع والمتبقي." action="فاتورة جديدة" onAction={onAdd} /><section className="panel"><PanelHeading title="كل الفواتير" /><div className="table-scroll"><table><thead><tr><th>رقم الفاتورة</th><th>العميل</th><th>التاريخ</th><th>الإجمالي</th><th>المدفوع</th><th>الحالة</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice._id}><td className="invoice-id">#{invoice._id.slice(-6).toUpperCase()}</td><td>{invoice.customerId?.name || customers.find((customer) => customer._id === invoice.customerId)?.name || 'غير معروف'}</td><td>{date(invoice.createdAt)}</td><td className="price">{money(invoice.subtotal)}</td><td className="price">{money(invoice.paid)}</td><td><span className={`invoice-status ${invoice.status}`}>{invoice.status === 'paid' ? 'مدفوعة' : invoice.status === 'partial' ? 'جزئية' : 'مستحقة'}</span></td></tr>)}</tbody></table>{!invoices.length && <EmptyState text="لم يتم إنشاء فواتير بعد" />}</div></section><p className="helper-note"><PackagePlus size={15} /> المنتجات المتاحة حاليًا: {products.length}</p></>; }
function PaymentsPage({ payments, invoices, customers, onAdd }) { return <><PageHeader eyebrow="التحصيل" title="المدفوعات" description="سجل الدفعات وتابع التحصيل من العملاء." action="تسجيل دفعة" onAction={onAdd} /><section className="panel"><PanelHeading title="سجل المدفوعات" /><div className="table-scroll"><table><thead><tr><th>العميل</th><th>الفاتورة</th><th>المبلغ</th><th>طريقة الدفع</th><th>التاريخ</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment._id}><td>{payment.customerId?.name || customers.find((customer) => customer._id === payment.customerId)?.name || 'غير معروف'}</td><td className="invoice-id">{payment.invoiceId?._id ? `#${payment.invoiceId._id.slice(-6).toUpperCase()}` : 'حساب عام'}</td><td className="price">{money(payment.amount)}</td><td>{payment.paymentMethod}</td><td>{date(payment.createdAt)}</td></tr>)}</tbody></table>{!payments.length && <EmptyState text="لم يتم تسجيل مدفوعات بعد" />}</div></section></>; }
function EmptyState({ text }) { return <div className="empty-state"><Box size={20} />{text}</div>; }
function Modal({ title, eyebrow, children, onClose, onSubmit, submitText }) { return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="modal" onSubmit={(event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }}><div className="modal-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button type="button" className="close-button" onClick={onClose}><X size={19} /></button></div>{children}<button className="primary-button submit-button" type="submit"><Plus size={17} /> {submitText}</button></form></div>; }
function ProductModal({ onClose, onSave }) { return <Modal title="إضافة منتج" eyebrow="مخزون جديد" onClose={onClose} submitText="حفظ المنتج" onSubmit={(form) => onSave({ name: form.get('name'), type: form.get('type'), quantity: Number(form.get('quantity')), purchasePrice: Number(form.get('purchasePrice')), sellingPrice: Number(form.get('sellingPrice')), minQuantity: Number(form.get('minQuantity')) })}><label>اسم المنتج<input name="name" required autoFocus placeholder="مثال: iPhone 15 Pro" /></label><div className="form-grid"><label>النوع<select name="type"><option>موبايل</option><option>إكسسوار</option><option>قطع غيار</option></select></label><label>الكمية<input name="quantity" required type="number" min="0" defaultValue="1" /></label><label>سعر الشراء<input name="purchasePrice" required type="number" min="0" defaultValue="0" /></label><label>سعر البيع<input name="sellingPrice" required type="number" min="0" defaultValue="0" /></label><label>حد التنبيه<input name="minQuantity" required type="number" min="0" defaultValue="3" /></label></div></Modal>; }
function CustomerModal({ onClose, onSave }) { return <Modal title="إضافة عميل" eyebrow="عميل جديد" onClose={onClose} submitText="حفظ العميل" onSubmit={(form) => onSave({ name: form.get('name'), phone: form.get('phone'), address: form.get('address'), balance: 0 })}><label>اسم العميل<input name="name" required autoFocus placeholder="الاسم بالكامل" /></label><div className="form-grid"><label>رقم الهاتف<input name="phone" required type="tel" placeholder="01xxxxxxxxx" /></label><label>العنوان<input name="address" placeholder="العنوان" /></label></div></Modal>; }
function InvoiceModal({ products, customers, onClose, onSave }) { const [items, setItems] = useState([]); const [productQuery, setProductQuery] = useState(''); const available = products.filter((product) => product.quantity > 0); const filteredProducts = available.filter((product) => `${product.name} ${product.type}`.toLocaleLowerCase().includes(productQuery.trim().toLocaleLowerCase()) && !items.some((item) => item.productId === product._id)); function addItem(product) { setItems([...items, { productId: product._id, name: product.name, quantity: 1, unitPrice: product.sellingPrice }]); setProductQuery(''); } const total = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); return <Modal title="فاتورة جديدة" eyebrow="عملية بيع" onClose={onClose} submitText="حفظ الفاتورة" onSubmit={(form) => onSave({ customerId: form.get('customerId'), items, paid: Number(form.get('paid') || 0) })}><label>العميل<select name="customerId" required><option value="">اختر العميل</option>{customers.map((customer) => <option key={customer._id} value={customer._id}>{customer.name} - {customer.phone}</option>)}</select></label><div className="product-search-field"><label htmlFor="invoice-product-search">ابحث عن منتج</label><div className="search-box invoice-search"><Search size={16} /><input id="invoice-product-search" value={productQuery} onChange={(event) => setProductQuery(event.target.value)} placeholder="اكتب اسم المنتج أو النوع..." /></div>{productQuery.trim() && <div className="product-search-results">{filteredProducts.length ? filteredProducts.map((product) => <button type="button" key={product._id} onClick={() => addItem(product)}><span><strong>{product.name}</strong><small>{product.type} · متاح {product.quantity}</small></span><b>{money(product.sellingPrice)}</b><Plus size={15} /></button>) : <p>لا توجد منتجات متاحة بهذا البحث</p>}</div>}</div>{items.map((item, index) => <div className="invoice-line" key={item.productId}><span>{item.name}</span><input type="number" min="1" max={products.find((product) => product._id === item.productId)?.quantity} value={item.quantity} onChange={(event) => setItems(items.map((current, itemIndex) => itemIndex === index ? { ...current, quantity: Number(event.target.value) } : current))} /><strong>{money(item.quantity * item.unitPrice)}</strong><button type="button" onClick={() => setItems(items.filter((current) => current.productId !== item.productId))}><X size={14} /></button></div>)}<div className="invoice-total"><span>الإجمالي</span><strong>{money(total)}</strong></div><label>المدفوع<input name="paid" type="number" min="0" max={total} defaultValue="0" /></label>{!items.length && <p className="form-hint">ابحث عن منتج واختره لإضافته إلى الفاتورة.</p>}</Modal>; }
function PaymentModal({ invoices, customers, onClose, onSave }) { return <Modal title="تسجيل دفعة" eyebrow="تحصيل" onClose={onClose} submitText="حفظ الدفعة" onSubmit={(form) => onSave({ customerId: form.get('customerId'), invoiceId: form.get('invoiceId') || undefined, amount: Number(form.get('amount')), paymentMethod: form.get('paymentMethod') })}><label>العميل<select name="customerId" required><option value="">اختر العميل</option>{customers.map((customer) => <option key={customer._id} value={customer._id}>{customer.name}</option>)}</select></label><label>الفاتورة (اختياري)<select name="invoiceId"><option value="">دفعة على الحساب</option>{invoices.filter((invoice) => invoice.remaining > 0).map((invoice) => <option key={invoice._id} value={invoice._id}>#{invoice._id.slice(-6).toUpperCase()} - {money(invoice.remaining)}</option>)}</select></label><div className="form-grid"><label>المبلغ<input name="amount" required type="number" min="0.01" step="0.01" /></label><label>طريقة الدفع<select name="paymentMethod"><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="transfer">تحويل</option><option value="instapay">InstaPay</option><option value="other">أخرى</option></select></label></div></Modal>; }
function SettingsModal({ storeName, defaultMinQuantity, onClose, onSave }) { return <Modal title="إعدادات المتجر" eyebrow="التفضيلات" onClose={onClose} submitText="حفظ الإعدادات" onSubmit={(form) => onSave({ name: form.get('storeName'), minQuantity: Number(form.get('minQuantity')) })}><label>اسم المتجر<input name="storeName" required defaultValue={storeName} /></label><div className="form-grid"><label>العملة<select defaultValue="EGP"><option value="EGP">جنيه مصري</option><option value="USD">دولار أمريكي</option></select></label><label>حد التنبيه الافتراضي<input name="minQuantity" type="number" min="0" defaultValue={defaultMinQuantity} /></label></div><div className="certificate-help"><strong>تفعيل HTTPS على الهاتف</strong><p>نزّل الشهادة من الهاتف ثم ثبّتها من إعدادات الأمان لإزالة تحذير الشهادة المحلية.</p><a className="certificate-download" href="/omar-shop-local.cer" download="omar-shop-local.cer"><Download size={15} /> تحميل شهادة HTTPS</a><small>Android: Security ← Install a certificate ← CA Certificate</small><small>iPhone: ثبّت Profile ثم فعّل الثقة من Certificate Trust Settings</small></div><p className="form-hint">يتم حفظ اسم المتجر وحد التنبيه على هذا الجهاز.</p></Modal>; }

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch((error) => console.error('Service worker registration failed:', error));
